aliTask1/urls.py
from django.conf.urls import url
from django.contrib import admin

from task1app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^question/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^question/new/$', views.QuestionView.as_view(), name='new'),
    url(r'^question/(?P<pk>[0-9]+)/new/$', views.ChoiceView.as_view(), name='choice'),

    #url(r'^question/(?P<pk>[0-9]+)/choice/$', views.ChoiceView.as_view(), name='answer'),
    url(r'^question/(?P<pk>[0-9]+)/delete/$', views.DeleteView.as_view(), name='delete'),
    url(r'^question/(?P<pk>[0-9]+)/choice/(?P<id>[0-9]+)/delete/$', views.DeleteViewChoice.as_view(), name='delete-choice'),
    url(r'^question/(?P<pk>[0-9]+)/vote/$', views.VoteView.as_view(), name='vote'),
]

task1app/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django import forms


class Question(models.Model):
    question_title = models.CharField(max_length=50, default='')
    question_text = models.CharField(max_length=300)
    question_date = models.DateTimeField("Publish Data", auto_now_add=True)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)

    choice_text = models.CharField(max_length=100, default='')
    choice_date = models.DateTimeField("Publish Data", auto_now_add=True)
    choice_result = models.IntegerField(default=0)

    def __str__(self):
        # type: () -> object
        return self.choice_text

task1app/forms.py
from django import forms
from task1app.models import Choice, Question


class QuestionForms(forms.ModelForm):
    class Meta:
        model = Question
        fields = {'question_title', 'question_text'}


class ChoiceForms(forms.ModelForm):
    class Meta:
        model = Choice
        fields = {'choice_text'}

task1app/views.py
# Create your views here.
from django.core.urlresolvers import reverse
from django.http import HttpResponse, request, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from task1app.models import Question, Choice
from task1app.forms import QuestionForms, ChoiceForms


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'lastest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-question_date')


class DetailView(generic.DetailView, generic.View):
    template_name = 'question_detail.html'
    model = Question

    def post(self, request, *args, **kwargs):
        if self.request.POST.get('choice'):
            ids = self.request.POST['choice']
            choice = Choice.objects.get(id=ids)
            choice.choice_result += 1
            choice.save()
            return HttpResponseRedirect('/question/%s/vote' % self.kwargs['pk'])
        else:
            return HttpResponseRedirect('/question/%s' % self.kwargs['pk'])


class QuestionView(generic.FormView):
    template_name = 'question.html'

    def get(self, request, *args, **kwargs):
        form = QuestionForms()

        return render(request, 'question.html', {'form': form})

    def post(self, request, *args, **kwargs):
        question_form = QuestionForms(self.request.POST)
        if question_form.is_valid():
            question_form.save()

        return HttpResponseRedirect('/')


class ChoiceView(generic.FormView):
    template_name = 'choice.html'
    fields = ['choice_text']

    def get(self, request, *args, **kwargs):
        form = ChoiceForms()

        return render(self.request, 'choice.html', {'form': form})

    def post(self, request, *args, **kwargs):
        choice_form = ChoiceForms(self.request.POST)
        if choice_form.is_valid():
            quest = Question.objects.get(id=self.kwargs['pk'])
            choice = choice_form.save(commit=False)
            choice.question = quest
            choice.save()

        return HttpResponseRedirect('/question/%s' % (self.kwargs['pk']))


class DeleteView(generic.DeleteView):
    model = Question
    template_name = 'delete.html'

    def get(self, request, *args, **kwargs):
        ids = self.kwargs['pk']
        quest = Question.objects.get(id=ids)
        quest.delete()

        return HttpResponseRedirect('/')


class DeleteViewChoice(generic.DeleteView):
    template_name = 'delete.html'

    def get(self, request, *args, **kwargs):
        ids = self.kwargs['id']
        choice = Choice.objects.get(id=ids)
        choice.delete()

        return HttpResponseRedirect('/question/%s' % (self.kwargs['pk']))


class VoteView(generic.DetailView):
    template_name = 'vote.html'
    model = Question

templates/answer.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Answer</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <style type="text/css">
            a{color:white}
        </style>
    </head>
    <body>
    {% extends 'up_bar.html' %}
    {% block content %}
        <div class="row">
            <div class="content">
                <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                        <h3 class="panel-title">{{ question.question_title }}</h3>
                        </div>
                        <div class="panel-body">
                            {{ question.question_text }}
                        </div>
                    </div>
                </div>
                </div>
                    <div class="col-md-4"></div>
                    <div style="float: left;">
                    <form action="" method="post">
                        <input type="hidden" value="{{ question.id }}" name="idd">
                    {% csrf_token %}
                    {{ form.as_ul }}
                        <input type="submit" value="Choice" class="btn btn-default">
                    </form>
                </div>
        </div>
    {% endblock content %}
    </body>
</html>

templates/choice.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Answer</title>
    </head>
    <body>
    {% extends 'up_bar.html' %}
    {% block content %}
        <span> New Choice </span>
                            <form action="" method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <input type="submit" class="btn btn-default" value="Add Choice" />
                            </form>

    {% endblock content %}
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="UTF-8">
        <title>Index</title>
    </head>
    <body>
    {% extends 'up_bar.html' %}
    {% block content %}
        {% if lastest_question_list %}
            {% for question in lastest_question_list.all %}
                <a href="{% url 'detail' question.id %}" >{{ question.question_title }}</a>|<a href="{% url 'delete' question.id  %}"> del </a></br>
            {% endfor %}
        {% else %}
            <p>Veri bulunmuyor.Soru Ekleyin.<a href="/question/new/">New Question</a></p>
        {% endif %}
        {% endblock content %}
    </body>
</html>

templates/question.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Answer</title>
    </head>
    <body>
    {% extends 'up_bar.html' %}
    {% block content %}
        <span> New Question </span>

                            <form action="" method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <input type="submit" class="btn btn-default" value="Add Question" />
                            </form>

    {% endblock content %}
    </body>
</html>

templates/question_detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Detail</title>
        <style type="text/css">
            li{list-style: none;}
        </style>
    </head>
    <body>
        {% extends 'up_bar.html' %}
        {% block content %}
        <span>Question</span> : <span> {{ question.question_text }} </span>
        </br>
            <form method="POST">
            {% csrf_token %}
                {% if question.choice_set.count > 0 %}
                    {% for choice in question.choice_set.all %}
                        <input type="radio" name="choice" id="{{ choice.id }}" value="{{ choice.id }}">{{ choice.choice_text }} |<a href="{% url 'delete-choice' question.id choice.id %}">X</a> <br>
                    {% endfor %}
                <input type="submit" value="Vote"></br>
            </form>
                {% else %}
                    <p>no choices</p>
                {% endif %}
                <a href="{% url 'choice' question.id %}">Add Choice</a>

    {% endblock content %}
    </body>
</html>

templates/up_bar.html
<a href="/">Home</a> <br>
<a href="/question/new/">New Question</a> <br><br>
{% block content %}
{% endblock  %}

templates/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vote</title>
</head>
<body>
{% extends 'up_bar.html' %}
        {% block content %}
    {% if question.choice_set %}
        {% for choice in question.choice_set.all %}
            {{ choice.choice_text }} -> {{ choice.choice_result }} <br>
        {% endfor %}
    {% endif %}
{% endblock %}
</body>
</html>